# Generated by Django 4.1.1 on 2022-10-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(max_length=120)),
                ('roll', models.JSONField(max_length=100)),
                ('city', models.JSONField(max_length=120)),
            ],
        ),
    ]
